export const FoodMenu = [
  {
    id: "bo-ssam-dinner-for-4-6",
    img: "https://goldbelly.imgix.net/uploads/showcase_media_asset/image/110906/bo-ssam-dinner-for-4.c4a32e8801e2f0283e0565bbe8493149.jpg?ixlib=react-9.0.2&auto=format&ar=1%3A1",
    name: "Momofuku",
    dsc: "Half Bo Ssäm Dinner for 4-6",
    price: 169,
    rate: 4,
    country: "New York, NY",
  },
  {
    id: "legendary-seafood-gumbo",
    img: "https://goldbelly.imgix.net/uploads/showcase_media_asset/image/133100/legendary-seafood-gumbo.a4010efb8ba0569ff59d68c3723f0963.jpg?ixlib=react-9.0.2&auto=format&ar=1%3A1",
    name: "Commander's Palace",
    dsc: "Legendary Seafood Gumbo",
    price: 89,
    rate: 4,
    country: "New Orleans, LA",
  },
  {
    id: "the-gramercy-tavern-burger-4-pack",
    img: "https://goldbelly.imgix.net/uploads/showcase_media_asset/image/137148/Gramercy-Tavern-Burger-and-Kielbasa-Kit-6.4.21-72ppi-1x1-15.jpg?ixlib=react-9.0.2&auto=format&ar=1%3A1",
    name: "Gramercy Tavern",
    dsc: "The Gramercy Tavern Burger - 4 Pack",
    price: 99,
    rate: 4,
    country: "New York, NY",
  },
  {
    id: "the-coop-complete-fried-chicken-dinner-for-4",
    img: "https://goldbelly.imgix.net/uploads/showcase_media_asset/image/134235/complete-fried-chicken-dinner-for-4.aeabf841c124b9cc2fb0166f27790999.jpg?ixlib=react-9.0.2&auto=format&ar=1%3A1",
    name: "Blue Ribbon",
    dsc: '"The Coop" Complete Fried Chicken Dinner for 4',
    price: 119,
    rate: 4,
    country: "New York, NY",
  },
  {
    id: "traditional-beef-empanadas-with-llajua-sauce-12-pack",
    img: "https://goldbelly.imgix.net/uploads/showcase_media_asset/image/132987/traditional-meat-empanadas-with-llajua-sauce-12-pack.f2adcfeb4ccf027675047f1367ce83ca.jpg?ixlib=react-9.0.2&auto=format&ar=1%3A1",
    name: "Chef Francis Mallmann",
    dsc: "Traditional Beef Empanadas with Llajua Sauce - 12 Pack",
    price: 99,
    rate: 4,
    country: "Patagonia, Argentina",
  },
  {
    id: "pork-buns-12-pack",
    img: "https://goldbelly.imgix.net/uploads/showcase_media_asset/image/110984/pork-buns-12-pack.67a379b014b23c7fd944ab48b9e720f6.jpg?ixlib=react-9.0.2&auto=format&ar=1%3A1",
    name: "Momofuku",
    dsc: "Pork Buns - 12 Pack",
    price: 119,
    rate: 4,
    country: "New York, NY",
  },
  {
    id: "hot-honey-chicken-and-cornbread-waffles-for-2",
    img: "https://goldbelly.imgix.net/uploads/showcase_media_asset/image/131336/marcus-hot-honey-chicken-and-cornbread-waffles-kit-for-4.618df9b9613b506f65c8342ab2e28b32.jpg?ixlib=react-9.0.2&auto=format&ar=1%3A1",
    name: "Marcus Samuelsson's Streetbird",
    dsc: "Marcus’ Hot Honey Chicken & Cornbread Waffles Kit for 4",
    price: 99,
    rate: 5,
    country: "Harlem, NY",
  },
  {
    id: "zahav-hummus-and-salatim-spread",
    img: "https://goldbelly.imgix.net/uploads/showcase_media_asset/image/114579/zahav-hummus-and-salatim-spread-for-6-8.137df09ea04ec063480f58ead8fe4b83.png?ixlib=react-9.0.2&auto=format&ar=1%3A1",
    name: "Zahav",
    dsc: "Zahav Hummus & Salatim Spread",
    price: 99,
    rate: 4,
    country: "Philadelphia, PA",
  },
  {
    id: "wood-fired-pizzas-best-seller-4-pack",
    img: "https://goldbelly.imgix.net/uploads/showcase_media_asset/image/106027/wood-fired-pizzas-best-seller-4-pack.1653bb05922ba153ac178f8365d27f6d.jpg?ixlib=react-9.0.2&auto=format&ar=1%3A1",
    name: "Pizzeria Bianco",
    dsc: "Wood Fired Pizzas Best Seller - 4 Pack",
    price: 129,
    rate: 5,
    country: "Phoenix, AZ",
  },
  {
    id: "gramercy-tavern-mushroom-lasagna-for-4",
    img: "https://goldbelly.imgix.net/uploads/showcase_media_asset/image/134704/gramercy-tavern-mushroom-lasagna-4-pack.88c671dec184d8bee908d6f5d8d860f9.jpg?ixlib=react-9.0.2&auto=format&ar=1%3A1",
    name: "Gramercy Tavern",
    dsc: "Gramercy Tavern Mushroom Lasagna for 4",
    price: 99,
    rate: 4,
    country: "New York, NY",
  },
  {
    id: "brown-butter-lobster-roll-kit-4-pack",
    img: "https://goldbelly.imgix.net/uploads/showcase_media_asset/image/133343/brown-butter-lobster-roll-kit-4-pack.f97b1254243c8628ad1a5cd41227f5d7.jpg?ixlib=react-9.0.2&auto=format&ar=1%3A1",
    name: "Eventide Oyster Co.",
    dsc: "Brown Butter Lobster Roll Kit - 4 Pack",
    price: 99,
    rate: 5,
    country: "Portland, ME",
  },
  {
    id: "commanders-palace-three-course-dinner-for-2-shrimp-and-grits",
    img: "https://goldbelly.imgix.net/uploads/showcase_media_asset/image/104768/commanders-palace-three-course-shrimp-and-grits-dinner-for-2.984253533e589547e834420efccc174a.jpg?ixlib=react-9.0.2&auto=format&ar=1%3A1",
    name: "Commander's Palace",
    dsc: "Commander's Palace Three-Course Shrimp & Grits Dinner for 2",
    price: 169,
    rate: 4,
    country: "New Orleans, LA",
  },
  {
    id: "butchers-feast-for-4",
    img: "https://goldbelly.imgix.net/uploads/showcase_media_asset/image/104628/butchers-feast-for-4.cf40ca583a3bc2de78ac6355ee4b2995.jpg?ixlib=react-9.0.2&auto=format&ar=1%3A1",
    name: "Cote Korean Steakhouse",
    dsc: "The Original Butcher's Feast® for 4",
    price: 259,
    rate: 5,
    country: "New York, NY",
  },
  {
    id: "whole-peking-duck-kit-for-4",
    img: "https://goldbelly.imgix.net/uploads/showcase_media_asset/image/132862/decoys-whole-peking-duck-for-4.36f80dd5235f5495f279ed8765c33167.jpg?ixlib=react-9.0.2&auto=format&ar=1%3A1",
    name: "RedFarm",
    dsc: "Whole Peking Duck Kit for 4",
    price: 139,
    rate: 5,
    country: "New York, NY",
  },
  {
    id: "unconventional-texas-bbq-sampler-for-4-6",
    img: "https://goldbelly.imgix.net/uploads/showcase_media_asset/image/126766/unconventional-texas-bbq-sampler-for-4-6.ee40a926a0863ceeb13b1eafb987c7d1.jpg?ixlib=react-9.0.2&auto=format&ar=1%3A1",
    name: "Underbelly by Chris Shepherd",
    dsc: "Unconventional Texas BBQ Sampler for 4-6",
    price: 119,
    rate: 5,
    country: "Houston, TX",
  },
  {
    id: "diy-kit-for-2",
    img: "https://goldbelly.imgix.net/uploads/showcase_media_asset/image/113695/traditional-negiri-sushi-and-cutroll-kit-for-2.381bee7a4e1be32ad5818d93524b0bef.jpg?ixlib=react-9.0.2&auto=format&ar=1%3A1",
    name: "Blue Ribbon Sushi",
    dsc: "Blue Ribbon Sushi - DIY Kit for 2",
    price: 129,
    rate: 5,
    country: "New York, NY",
  },
  {
    id: "zahav-lamb-shoulder-meal-kit",
    img: "https://goldbelly.imgix.net/uploads/showcase_media_asset/image/114544/zahav-lamb-shoulder-meal-kit-for-4-6.58cfa4d3d5eca52ac45b2d37a9d0f2d4.png?ixlib=react-9.0.2&auto=format&ar=1%3A1",
    name: "Zahav",
    dsc: "Zahav Lamb Shoulder Meal Kit",
    price: 249,
    rate: 5,
    country: "Philadelphia, PA",
  },
  {
    id: "the-classic-plateau-dinner-for-2",
    img: "https://goldbelly.imgix.net/uploads/showcase_media_asset/image/131364/the-classic-plateau-dinner-for-2.9906825037a76931415a8fb5e8a2dcbd.jpg?ixlib=react-9.0.2&auto=format&ar=1%3A1",
    name: "Blue Ribbon",
    dsc: "The Classic Plateau Seafood Dinner for 2",
    price: 139,
    rate: 5,
    country: "New York, NY",
  },
  {
    id: "mac-and-cheese-chicken-pot-pie-combo-for-4",
    img: "https://goldbelly.imgix.net/uploads/showcase_media_asset/image/112776/mac-and-cheese-chicken-pot-pie-combo-for-4.c77be8dcb4fabfa1870a2ff4a6bd4c6a.jpg?ixlib=react-9.0.2&auto=format&ar=1%3A1",
    name: "Wolfgang Puck Catering",
    dsc: "Mac and Cheese + Chicken Pot Pie Combo for 4",
    price: 129,
    rate: 4,
    country: "Los Angeles, CA",
  },
  {
    id: "prime-galbi-steak-feast-for-4",
    img: "https://goldbelly.imgix.net/uploads/showcase_media_asset/image/104674/prime-galbi-steak-feast-for-4.51c78b5ba768078b166fe91325e60edc.jpg?ixlib=react-9.0.2&auto=format&ar=1%3A1",
    name: "Cote Korean Steakhouse",
    dsc: "Prime Galbi Steak Feast for 4",
    price: 249,
    rate: 5,
    country: "New York, NY",
  },
  {
    id: "dry-aged-boneless-ribeye-steak-dinner-kit-for-4",
    img: "https://goldbelly.imgix.net/uploads/showcase_media_asset/image/126887/dry-aged-boneless-ribeye-steak-dinner-for-4.81c3bdc05fe6bdb2c2214709863120e0.jpg?ixlib=react-9.0.2&auto=format&ar=1%3A1",
    name: "Chef Francis Mallmann",
    dsc: "Dry-Aged Boneless Ribeye Steak Dinner Kit for 4",
    price: 225,
    rate: 4,
    country: "Patagonia, Argentina",
  },
];
